packages:
  - .
  - apps/*
  - libs/*
  - tools/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - electron
  - electron-ipc-module
  - electron-winstaller
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
  - nx
  - rollup-plugin-electron-run
  - unrs-resolver

packageExtensions:
  electron-ipc-module@*:
    dependencies:
      typescript: ~6.0.2
  rollup-plugin-electron-run@*:
    dependencies:
      typescript: ~6.0.2

strictDepBuilds: false
