/**
 * GENERATED by `pnpm gen:fonts` — do not edit by hand.
 * Curated metadata lives in `scripts/font-overlay.mjs`.
 */

export interface FontChoice {
  /** The family name, exactly as Google spells it. */
  family: string;
  /** The weights Google actually serves. Asking for one it does not have 400s. */
  weights: readonly number[];
  /** Whether the face carries programming ligatures (`=>`, `!==`, `->`). */
  ligatures: boolean;
  /** Shown under the name in the picker. */
  note: string;
}

/**
 * The one entry that is not a Google font: whatever the machine calls its
 * monospace. Always available, never fetched, and the honest choice for anyone
 * who has already installed the font they want to code in.
 */
export const SYSTEM_FONT = 'System monospace';

export const FONT_CATALOGUE: readonly FontChoice[] = [
  {
    family: SYSTEM_FONT,
    weights: [300, 400, 500, 600, 700],
    ligatures: false,
    note: 'Whatever this machine uses for code',
  },
  {
    family: 'JetBrains Mono',
    weights: [300, 400, 500, 600, 700],
    ligatures: true,
    note: 'Tall x-height, made for long sessions',
  },
  {
    family: 'Fira Code',
    weights: [300, 400, 500, 600, 700],
    ligatures: true,
    note: 'The font that popularised code ligatures',
  },
  {
    family: 'Victor Mono',
    weights: [300, 400, 500, 600, 700],
    ligatures: true,
    note: 'Cursive italics, semi-connected ligatures',
  },
  {
    family: 'Source Code Pro',
    weights: [300, 400, 500, 600, 700],
    ligatures: false,
    note: 'Adobe’s workhorse, unfussy and legible',
  },
  {
    family: 'IBM Plex Mono',
    weights: [300, 400, 500, 600, 700],
    ligatures: false,
    note: 'Warm and slightly humanist',
  },
  {
    family: 'Roboto Mono',
    weights: [300, 400, 500, 600, 700],
    ligatures: false,
    note: 'Neutral, familiar, hard to dislike',
  },
  {
    family: 'Inconsolata',
    weights: [300, 400, 500, 600, 700],
    ligatures: false,
    note: 'Narrow, fits a lot of GLSL on a line',
  },
  {
    family: 'Noto Sans Mono',
    weights: [300, 400, 500, 600, 700],
    ligatures: false,
    note: 'Enormous character coverage',
  },
  {
    family: 'Geist Mono',
    weights: [300, 400, 500, 600, 700],
    ligatures: false,
    note: 'Crisp and geometric',
  },
  {
    family: 'Red Hat Mono',
    weights: [300, 400, 500, 600, 700],
    ligatures: false,
    note: 'Open apertures, low contrast',
  },
  {
    family: 'Spline Sans Mono',
    weights: [300, 400, 500, 600, 700],
    ligatures: false,
    note: 'Rounded terminals, gentle on the eye',
  },
  {
    family: 'Azeret Mono',
    weights: [300, 400, 500, 600, 700],
    ligatures: false,
    note: 'Sturdy and squared-off',
  },
  {
    family: 'Martian Mono',
    weights: [300, 400, 500, 600, 700],
    ligatures: false,
    note: 'Wide and deliberate',
  },
  {
    family: 'Overpass Mono',
    weights: [300, 400, 500, 600, 700],
    ligatures: false,
    note: 'Based on US highway signage',
  },
  {
    family: 'Reddit Mono',
    weights: [300, 400, 500, 600, 700],
    ligatures: false,
    note: 'Compact, quietly modern',
  },
  {
    family: 'Chivo Mono',
    weights: [300, 400, 500, 600, 700],
    ligatures: false,
    note: 'Grotesque bones, plenty of weight',
  },
  {
    family: 'DM Mono',
    weights: [300, 400, 500],
    ligatures: false,
    note: 'Light and airy; no bold',
  },
  {
    family: 'Sometype Mono',
    weights: [400, 500, 600, 700],
    ligatures: false,
    note: 'Typewriter warmth, screen legibility',
  },
  {
    family: 'Space Mono',
    weights: [400, 700],
    ligatures: false,
    note: 'Quirky, characterful, not for everyone',
  },
  {
    family: 'Ubuntu Mono',
    weights: [400, 700],
    ligatures: false,
    note: 'Small on the page; set it a size up',
  },
  {
    family: 'Cousine',
    weights: [400, 700],
    ligatures: false,
    note: 'Metric-compatible with Courier New',
  },
  {
    family: 'Anonymous Pro',
    weights: [400, 700],
    ligatures: false,
    note: 'Designed for the coding of ambiguities',
  },
  {
    family: 'Courier Prime',
    weights: [400, 700],
    ligatures: false,
    note: 'Courier, redrawn to be readable',
  },
  {
    family: 'Nanum Gothic Coding',
    weights: [400, 700],
    ligatures: false,
    note: 'Latin plus full Hangul',
  },
  {
    family: 'Share Tech Mono',
    weights: [400],
    ligatures: false,
    note: 'Techy and narrow; one weight only',
  },
  {
    family: 'PT Mono',
    weights: [400],
    ligatures: false,
    note: 'Made for forms and tables',
  },
  {
    family: 'Fragment Mono',
    weights: [400],
    ligatures: false,
    note: 'Helvetica’s monospaced cousin',
  },
];
