/**
 * Builds the official plugin packages and the release catalogue.
 *
 * Sources live in `plugins/official/<name>/`: a `manifest.json`, a
 * `listing.json` (catalogue-only text such as the description) and
 * `src/index.ts`, the Worker entry. Each package's code is bundled with
 * esbuild into one self-contained script — no imports left, nothing loaded at
 * run time — and written beside the catalogue in `apps/studio/src/plugins/`,
 * which the app ships as assets (`plugins/…` under its base URL).
 *
 * `plugins/official/release.json` lists which packages this release's
 * catalogue offers, in order; a package can be built and tested before it is
 * listed. The output is deterministic: run with `--check` to fail when the
 * committed files are not what the sources build (`pnpm check:plugins`).
 */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

import { buildSync } from 'esbuild';

import {
  CATALOGUE_FORMAT,
  parsePluginPackage,
  validateCatalogue,
  type CatalogueEntry,
  type PluginCatalogue,
} from '@shadergrove/shared/plugin';

import { createLogger } from '../lib/logger.js';
import { root } from '../lib/paths.js';

const log = createLogger('official-plugins');
const sourceDir = resolve(root, 'plugins/official');
export const outputDir = resolve(root, 'apps/studio/src/plugins');

/** What a Worker bundle must never contain: it gets no network, DOM or dynamic code. */
const FORBIDDEN = [
  /\bfetch\s*\(/,
  /\bXMLHttpRequest\b/,
  /\bWebSocket\b/,
  /\bimportScripts\b/,
  /\bimport\s*\(/,
  /\beval\s*\(/,
  /\bnew\s+Function\b/,
  /\bdocument\./,
];

interface Listing {
  description: string;
}

/** Bundle one package's Worker code and assemble its `.sgplugin.json` text. */
export function buildPackage(name: string): { fileName: string; text: string; listing: Listing } {
  const dir = resolve(sourceDir, name);
  const manifest = JSON.parse(readFileSync(resolve(dir, 'manifest.json'), 'utf8')) as {
    id: string;
    version: string;
  };
  const listing = JSON.parse(readFileSync(resolve(dir, 'listing.json'), 'utf8')) as Listing;
  const result = buildSync({
    absWorkingDir: root,
    entryPoints: [relative(root, resolve(dir, 'src/index.ts'))],
    bundle: true,
    write: false,
    format: 'iife',
    platform: 'neutral',
    target: 'es2022',
    charset: 'utf8',
    legalComments: 'none',
    treeShaking: true,
    minifySyntax: true,
    logLevel: 'silent',
  });
  const code = `// ${manifest.id} ${manifest.version} — generated by tools/workspace/src/generate/official-plugins.ts\n${result.outputFiles[0]!.text}`;
  for (const pattern of FORBIDDEN) {
    if (pattern.test(code)) throw new Error(`${name}: the Worker bundle must not use ${pattern}`);
  }
  const text = `${JSON.stringify({ manifest, code }, null, 2)}\n`;
  const parsed = parsePluginPackage(text);
  if (!parsed.ok) throw new Error(`${name}: ${parsed.errors.join('; ')}`);
  return { fileName: `${manifest.id}-${manifest.version}.sgplugin.json`, text, listing };
}

/** Every generated file, by name in `outputDir`. */
export function buildOfficialPlugins(): Map<string, string> {
  const release = JSON.parse(readFileSync(resolve(sourceDir, 'release.json'), 'utf8')) as {
    packages: string[];
  };
  const files = new Map<string, string>();
  const packages: CatalogueEntry[] = [];
  for (const name of release.packages) {
    const built = buildPackage(name);
    const parsed = parsePluginPackage(built.text);
    if (!parsed.ok) throw new Error(parsed.errors.join('; '));
    const { manifest } = parsed.value;
    const bytes = Buffer.from(built.text, 'utf8');
    files.set(built.fileName, built.text);
    packages.push({
      id: manifest.id,
      version: manifest.version,
      name: manifest.name,
      description: built.listing.description,
      publisher: manifest.publisher,
      license: manifest.license,
      protocolVersion: manifest.protocolVersion,
      appVersionRange: manifest.appVersionRange,
      file: built.fileName,
      bytes: bytes.byteLength,
      sha256: createHash('sha256').update(bytes).digest('hex'),
      contributions: manifest.contributions.map(({ kind, id, name: label }) => ({
        kind,
        id,
        name: label,
      })),
    });
  }
  const catalogue: PluginCatalogue = { format: CATALOGUE_FORMAT, packages };
  const valid = validateCatalogue(catalogue);
  if (!valid.ok) throw new Error(`catalogue: ${valid.errors.join('; ')}`);
  files.set('catalogue.json', `${JSON.stringify(catalogue, null, 2)}\n`);
  return files;
}

function run(check: boolean): void {
  const files = buildOfficialPlugins();
  const existing = existsSync(outputDir) ? readdirSync(outputDir) : [];
  if (check) {
    const problems: string[] = [];
    for (const [name, text] of files) {
      const path = resolve(outputDir, name);
      if (!existsSync(path)) problems.push(`missing ${name}`);
      else if (readFileSync(path, 'utf8').replace(/\r\n/g, '\n') !== text) {
        problems.push(`stale ${name}`);
      }
    }
    for (const name of existing) if (!files.has(name)) problems.push(`unexpected ${name}`);
    if (problems.length > 0) {
      log.error(
        `Official plugins are out of date (${problems.join(', ')}); run pnpm generate:plugins`,
      );
      process.exit(1);
    }
    log.info(`Official plugins are up to date (${files.size} files)`);
    return;
  }
  mkdirSync(outputDir, { recursive: true });
  for (const name of existing) if (!files.has(name)) rmSync(resolve(outputDir, name));
  for (const [name, text] of files) writeFileSync(resolve(outputDir, name), text);
  log.info(`Wrote ${files.size} files to ${relative(root, outputDir)}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  run(process.argv.includes('--check'));
}
